version: '3.7'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'finance'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: 'docker'
    ports:
      - 3306:3306
    volumes:
      - './db_data:/var/lib/mysql'